joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['drivewhl_l_joint']
  right_wheel: ['drivewhl_r_joint']
  publish_rate: 50
  wheel_separation: 0.4
  wheel_radius: 0.1
  base_frame_id: base_footprint
  odom_frame_id: odom
  enable_odom_tf: true
  cmd_vel_timeout: 0.5
  velocity_rolling_window_size: 10
  use_stamped_vel: false
  pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

  open_loop: true
  enable_odom_tf: true
gazebo_ros_control:
  pid_gains:
    drivewhl_l_joint: {p: 10.0, i: 0.0, d: 0.0}
    drivewhl_r_joint: {p: 10.0, i: 0.0, d: 0.0}




#cmd_vel_timeout: 0.5
#publish_limited_velocity: true

